name: Build Windows EXE
on: [workflow_dispatch]  # 手动触发编译

jobs:
  build:
    runs-on: windows-latest  # 使用Windows编译环境
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile Program
      run: |
        g++ -o AutoScroll.exe autoscroll.cpp -luser32 -lgdi32 -mwindows

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AutoScroll.exe
        path: AutoScroll.exe
